# Generated by Django 2.2.14 on 2022-02-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Payment',
        ),
    ]
